// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqqlrnwznjtlepgtrcmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcWxybnd6bmp0bGVwZ3RyY21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2Mzc1ODksImV4cCI6MjA1NTIxMzU4OX0.7DSDgARBKNqUHLpJUNHNeLkak3yUmDuy3SyiZ6W2pfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);